package sync

import (
	"encoding/json"
	"errors"
	"testing"

	"github.com/mattermost/mattermost/server/public/model"
	"github.com/mattermost/mattermost/server/public/plugin/plugintest"
	"github.com/mattermost/mattermost/server/public/pluginapi"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

func testFieldDefinitions() []FieldDefinition {
	return []FieldDefinition{
		{
			Name:        "job_title",
			DisplayName: "Job Title",
			Type:        model.PropertyFieldTypeText,
			AccessMode:  model.PropertyAccessModePublic,
		},
		{
			Name:        "programs",
			DisplayName: "Programs",
			Type:        model.PropertyFieldTypeMultiselect,
			Options: []model.CustomProfileAttributesSelectOption{
				{Name: "Apples"},
				{Name: "Oranges"},
				{Name: "Lemons"},
				{Name: "Grapes"},
			},
			AccessMode: model.PropertyAccessModeSharedOnly,
		},
		{
			Name:        "clearance",
			DisplayName: "Clearance",
			Type:        model.PropertyFieldTypeRank,
			Options: []model.CustomProfileAttributesSelectOption{
				{Name: "CUI", Rank: model.NewPointer(1)},
				{Name: "Confidential", Rank: model.NewPointer(2)},
				{Name: "Secret", Rank: model.NewPointer(3)},
				{Name: "Top Secret", Rank: model.NewPointer(4)},
			},
			AccessMode: model.PropertyAccessModeSharedOnly,
		},
		{
			Name:        "start_date",
			DisplayName: "Start Date",
			Type:        model.PropertyFieldTypeDate,
			AccessMode:  model.PropertyAccessModeSourceOnly,
		},
	}
}

func TestSyncFields(t *testing.T) {
	groupID := "test-group-id"
	pluginID := "test-plugin-id"
	defs := testFieldDefinitions()

	t.Run("creates all fields and returns ID cache", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock GetPropertyFieldByName returning not found (fields don't exist yet)
		api.On("GetPropertyFieldByName", groupID, "", "job_title").Return(nil, errors.New("not found")).Once()
		api.On("GetPropertyFieldByName", groupID, "", "programs").Return(nil, errors.New("not found")).Once()
		api.On("GetPropertyFieldByName", groupID, "", "clearance").Return(nil, errors.New("not found")).Once()
		api.On("GetPropertyFieldByName", groupID, "", "start_date").Return(nil, errors.New("not found")).Once()

		// Mock field creation - ID is generated by Mattermost
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "job_title" && f.ID == ""
		})).Return(&model.PropertyField{ID: "generated_id_1", Name: "job_title", Type: model.PropertyFieldTypeText}, nil)

		programsField := &model.PropertyField{
			ID:   "generated_id_2",
			Name: "programs",
			Type: model.PropertyFieldTypeMultiselect,
			Attrs: model.StringInterface{
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_1", "name": "Apples"},
					map[string]interface{}{"id": "opt_id_2", "name": "Oranges"},
					map[string]interface{}{"id": "opt_id_3", "name": "Lemons"},
				},
			},
		}
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "programs" && f.ID == ""
		})).Return(programsField, nil)

		clearanceField := &model.PropertyField{
			ID:   "generated_id_3",
			Name: "clearance",
			Type: model.PropertyFieldTypeRank,
			Attrs: model.StringInterface{
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_4", "name": "CUI", "rank": 1},
					map[string]interface{}{"id": "opt_id_5", "name": "Confidential", "rank": 2},
					map[string]interface{}{"id": "opt_id_6", "name": "Secret", "rank": 3},
					map[string]interface{}{"id": "opt_id_7", "name": "Top Secret", "rank": 4},
				},
			},
		}
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "clearance" && f.ID == ""
		})).Return(clearanceField, nil)

		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "start_date" && f.ID == ""
		})).Return(&model.PropertyField{ID: "generated_id_4", Name: "start_date", Type: model.PropertyFieldTypeDate}, nil)

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID, defs)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, "generated_id_1", cache.GetFieldID("job_title"))
		assert.Equal(t, "generated_id_2", cache.GetFieldID("programs"))
		assert.Equal(t, "generated_id_3", cache.GetFieldID("clearance"))
		assert.Equal(t, "generated_id_4", cache.GetFieldID("start_date"))
		assert.Equal(t, model.PropertyFieldTypeText, cache.GetFieldType("job_title"))
		assert.Equal(t, model.PropertyFieldTypeMultiselect, cache.GetFieldType("programs"))
		assert.Equal(t, model.PropertyFieldTypeRank, cache.GetFieldType("clearance"))
		assert.Equal(t, model.PropertyFieldTypeDate, cache.GetFieldType("start_date"))
		assert.Equal(t, "opt_id_1", cache.GetOptionID("programs", "Apples"))
		assert.Equal(t, "opt_id_2", cache.GetOptionID("programs", "Oranges"))
		assert.Equal(t, "opt_id_3", cache.GetOptionID("programs", "Lemons"))
		assert.Equal(t, "opt_id_4", cache.GetOptionID("clearance", "CUI"))
		assert.Equal(t, "opt_id_5", cache.GetOptionID("clearance", "Confidential"))
		assert.Equal(t, "opt_id_6", cache.GetOptionID("clearance", "Secret"))
		assert.Equal(t, "opt_id_7", cache.GetOptionID("clearance", "Top Secret"))
		api.AssertExpectations(t)
	})

	t.Run("updates existing fields", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock GetPropertyFieldByName for each field (simulating they exist)
		existingJobTitle := &model.PropertyField{
			ID:      "existing_id_1",
			GroupID: groupID,
			Name:    "job_title",
			Type:    model.PropertyFieldTypeText,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
			},
		}
		api.On("GetPropertyFieldByName", groupID, "", "job_title").Return(existingJobTitle, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_1"
		})).Return(existingJobTitle, nil).Once()

		existingPrograms := &model.PropertyField{
			ID:      "existing_id_2",
			GroupID: groupID,
			Name:    "programs",
			Type:    model.PropertyFieldTypeMultiselect,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_1", "name": "Apples"},
					map[string]interface{}{"id": "opt_id_2", "name": "Oranges"},
					map[string]interface{}{"id": "opt_id_3", "name": "Lemons"},
				},
			},
		}
		api.On("GetPropertyFieldByName", groupID, "", "programs").Return(existingPrograms, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_2"
		})).Return(existingPrograms, nil).Once()

		existingClearance := &model.PropertyField{
			ID:      "existing_id_3",
			GroupID: groupID,
			Name:    "clearance",
			Type:    model.PropertyFieldTypeRank,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_4", "name": "CUI", "rank": 1},
					map[string]interface{}{"id": "opt_id_5", "name": "Confidential", "rank": 2},
					map[string]interface{}{"id": "opt_id_6", "name": "Secret", "rank": 3},
					map[string]interface{}{"id": "opt_id_7", "name": "Top Secret", "rank": 4},
				},
			},
		}
		api.On("GetPropertyFieldByName", groupID, "", "clearance").Return(existingClearance, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_3"
		})).Return(existingClearance, nil).Once()

		existingStartDate := &model.PropertyField{
			ID:      "existing_id_4",
			GroupID: groupID,
			Name:    "start_date",
			Type:    model.PropertyFieldTypeDate,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
			},
		}
		api.On("GetPropertyFieldByName", groupID, "", "start_date").Return(existingStartDate, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_4"
		})).Return(existingStartDate, nil).Once()

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID, defs)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, "existing_id_1", cache.GetFieldID("job_title"))
		assert.Equal(t, "existing_id_2", cache.GetFieldID("programs"))
		assert.Equal(t, "existing_id_3", cache.GetFieldID("clearance"))
		assert.Equal(t, "existing_id_4", cache.GetFieldID("start_date"))
		api.AssertExpectations(t)
	})

	t.Run("multiselect & rank fields include options", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock GetPropertyFieldByName returning not found for all fields
		api.On("GetPropertyFieldByName", groupID, "", mock.Anything).Return(nil, errors.New("not found"))

		// Mock field creation - verify Programs field has options
		multiSelectOptionsVerified := false
		rankOptionsVerified := false
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			if f.Name == "programs" {
				// Verify Programs field has correct options (Apples, Oranges, Lemons, Grapes)
				options, ok := f.Attrs[model.PropertyFieldAttributeOptions].([]interface{})
				if ok && len(options) == 4 {
					multiSelectOptionsVerified = true
				}
			}
			if f.Name == "clearance" {
				options, ok := f.Attrs[model.PropertyFieldAttributeOptions].([]interface{})

				if ok && len(options) == 4 {
					// Check for Rank as well
					numRanks := 0
					for _, option := range options {
						opt, ok := option.(map[string]interface{})
						if !ok {
							break
						}
						_, ok = opt["rank"]
						if ok {
							numRanks++
						}
					}
					if numRanks == 4 {
						rankOptionsVerified = true
					}
				}
			}
			return true
		})).Return(func(f *model.PropertyField) (*model.PropertyField, error) {
			// Return field with generated ID
			f.ID = "gen_id_" + f.Name
			if f.Name == "programs" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt1", "name": "Apples"},
					map[string]interface{}{"id": "opt2", "name": "Oranges"},
					map[string]interface{}{"id": "opt3", "name": "Lemons"},
					map[string]interface{}{"id": "opt4", "name": "Grapes"},
				}
			}
			if f.Name == "clearance" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt5", "name": "CUI", "rank": 1},
					map[string]interface{}{"id": "opt6", "name": "Confidential", "rank": 2},
					map[string]interface{}{"id": "opt7", "name": "Secret", "rank": 3},
					map[string]interface{}{"id": "opt8", "name": "Top Secret", "rank": 4},
				}
			}
			return f, nil
		})

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID, defs)

		require.NoError(t, err)
		assert.True(t, multiSelectOptionsVerified, "Options should be verified during field creation")
		assert.True(t, rankOptionsVerified, "Ranks should be present on all rank field options")
		assert.NotNil(t, cache)
	})

	t.Run("continues on partial failures", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock GetPropertyFieldByName - all fields don't exist
		api.On("GetPropertyFieldByName", groupID, "", mock.Anything).Return(nil, errors.New("not found"))

		createCallCount := 0
		// First field creation fails, others succeed
		api.On("CreatePropertyField", mock.Anything).Return(func(f *model.PropertyField) (*model.PropertyField, error) {
			createCallCount++
			if createCallCount == 1 {
				// First call fails
				return nil, errors.New("API error")
			}
			// Subsequent calls succeed
			f.ID = "generated_id_" + f.Name
			if f.Name == "programs" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt1", "name": "Apples"},
				}
			}
			if f.Name == "clearance" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt5", "name": "CUI", "rank": 1},
				}
			}
			return f, nil
		})

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogError", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogWarn", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID, defs)

		// Should not return error (graceful degradation)
		require.NoError(t, err)
		require.NotNil(t, cache)
	})

	t.Run("empty list creates no fields", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID, nil)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Empty(t, cache.FieldNameToID)
		assert.Empty(t, cache.FieldNameToType)
		api.AssertExpectations(t)
	})
}

func TestFieldIDCache(t *testing.T) {
	t.Run("GetFieldID returns correct field IDs", func(t *testing.T) {
		cache := &FieldIDCache{
			FieldNameToID: map[string]string{
				"job_title":  "id1",
				"programs":   "id2",
				"clearance":  "id3",
				"start_date": "id4",
			},
		}
		assert.Equal(t, "id1", cache.GetFieldID("job_title"))
		assert.Equal(t, "id2", cache.GetFieldID("programs"))
		assert.Equal(t, "id3", cache.GetFieldID("clearance"))
		assert.Equal(t, "id4", cache.GetFieldID("start_date"))
	})

	t.Run("GetFieldID returns empty string for unknown field", func(t *testing.T) {
		cache := &FieldIDCache{
			FieldNameToID: make(map[string]string),
		}
		assert.Equal(t, "", cache.GetFieldID("unknown_field"))
	})

	t.Run("GetOptionID returns correct option IDs", func(t *testing.T) {
		cache := &FieldIDCache{
			OptionNameToID: map[string]string{
				"programs|Apples":  "opt1",
				"programs|Oranges": "opt2",
				"programs|Lemons":  "opt3",
			},
		}
		assert.Equal(t, "opt1", cache.GetOptionID("programs", "Apples"))
		assert.Equal(t, "opt2", cache.GetOptionID("programs", "Oranges"))
		assert.Equal(t, "opt3", cache.GetOptionID("programs", "Lemons"))
	})

	t.Run("GetOptionID returns empty string for unknown field", func(t *testing.T) {
		cache := &FieldIDCache{
			OptionNameToID: make(map[string]string),
		}
		assert.Equal(t, "", cache.GetOptionID("unknown", "Apples"))
	})

	t.Run("GetOptionID returns empty string for unknown option", func(t *testing.T) {
		cache := &FieldIDCache{
			OptionNameToID: make(map[string]string),
		}
		assert.Equal(t, "", cache.GetOptionID("programs", "Unknown"))
	})

	t.Run("GetFieldType returns declared types", func(t *testing.T) {
		cache := NewFieldIDCache()
		cache.FieldNameToType["job_title"] = model.PropertyFieldTypeText
		cache.FieldNameToType["clearance"] = model.PropertyFieldTypeRank
		assert.Equal(t, model.PropertyFieldTypeText, cache.GetFieldType("job_title"))
		assert.Equal(t, model.PropertyFieldTypeRank, cache.GetFieldType("clearance"))
		assert.Equal(t, model.PropertyFieldType(""), cache.GetFieldType("unknown_field"))
	})
}

func TestFieldDefinitionDefaults(t *testing.T) {
	tests := []struct {
		name                  string
		json                  string
		wantVisibility        string
		wantAccessMode        string
		wantPermissionField   model.PermissionLevel
		wantPermissionValues  model.PermissionLevel
		wantPermissionOptions model.PermissionLevel
	}{
		{
			name:                  "omitted keys use current defaults",
			json:                  `{"name":"job_title","display_name":"Job Title","type":"text"}`,
			wantVisibility:        model.PropertyFieldVisibilityAlways,
			wantAccessMode:        model.PropertyAccessModePublic,
			wantPermissionField:   model.PermissionLevelSysadmin,
			wantPermissionValues:  model.PermissionLevelSysadmin,
			wantPermissionOptions: model.PermissionLevelSysadmin,
		},
		{
			name:                  "public access_mode translates to empty string",
			json:                  `{"name":"job_title","access_mode":"public"}`,
			wantVisibility:        model.PropertyFieldVisibilityAlways,
			wantAccessMode:        model.PropertyAccessModePublic,
			wantPermissionField:   model.PermissionLevelSysadmin,
			wantPermissionValues:  model.PermissionLevelSysadmin,
			wantPermissionOptions: model.PermissionLevelSysadmin,
		},
		{
			name:                  "empty access_mode is public",
			json:                  `{"name":"job_title","access_mode":""}`,
			wantVisibility:        model.PropertyFieldVisibilityAlways,
			wantAccessMode:        model.PropertyAccessModePublic,
			wantPermissionField:   model.PermissionLevelSysadmin,
			wantPermissionValues:  model.PermissionLevelSysadmin,
			wantPermissionOptions: model.PermissionLevelSysadmin,
		},
		{
			name: "explicit values pass through",
			json: `{
				"name":"start_date",
				"access_mode":"source_only",
				"visibility":"hidden",
				"permission_field":"admin",
				"permission_values":"member",
				"permission_options":"none"
			}`,
			wantVisibility:        model.PropertyFieldVisibilityHidden,
			wantAccessMode:        model.PropertyAccessModeSourceOnly,
			wantPermissionField:   model.PermissionLevelAdmin,
			wantPermissionValues:  model.PermissionLevelMember,
			wantPermissionOptions: model.PermissionLevelNone,
		},
		{
			name:                  "unknown values pass through for the server to reject",
			json:                  `{"name":"x","access_mode":"nope","visibility":"never","permission_field":"root","permission_values":"root","permission_options":"root"}`,
			wantVisibility:        "never",
			wantAccessMode:        "nope",
			wantPermissionField:   model.PermissionLevel("root"),
			wantPermissionValues:  model.PermissionLevel("root"),
			wantPermissionOptions: model.PermissionLevel("root"),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var def FieldDefinition
			require.NoError(t, json.Unmarshal([]byte(tt.json), &def))
			assert.Equal(t, tt.wantVisibility, def.visibility())
			assert.Equal(t, tt.wantAccessMode, def.accessMode())
			assert.Equal(t, tt.wantPermissionField, *def.permissionField())
			assert.Equal(t, tt.wantPermissionValues, *def.permissionValues())
			assert.Equal(t, tt.wantPermissionOptions, *def.permissionOptions())
		})
	}
}
