package sync

import (
	"encoding/json"
	"errors"
	"testing"

	"github.com/mattermost/mattermost/server/public/model"
	"github.com/mattermost/mattermost/server/public/plugin/plugintest"
	"github.com/mattermost/mattermost/server/public/pluginapi"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

func testFieldDefinitions() []FieldDefinition {
	return []FieldDefinition{
		{
			Name:        "job_title",
			DisplayName: "Job Title",
			Type:        model.PropertyFieldTypeText,
			AccessMode:  model.PropertyAccessModePublic,
		},
		{
			Name:        "programs",
			DisplayName: "Programs",
			Type:        model.PropertyFieldTypeMultiselect,
			Options: []model.CustomProfileAttributesSelectOption{
				{Name: "Apples"},
				{Name: "Oranges"},
				{Name: "Lemons"},
				{Name: "Grapes"},
			},
			AccessMode: model.PropertyAccessModeSharedOnly,
		},
		{
			Name:        "clearance",
			DisplayName: "Clearance",
			Type:        model.PropertyFieldTypeRank,
			Options: []model.CustomProfileAttributesSelectOption{
				{Name: "CUI", Rank: model.NewPointer(1)},
				{Name: "Confidential", Rank: model.NewPointer(2)},
				{Name: "Secret", Rank: model.NewPointer(3)},
				{Name: "Top Secret", Rank: model.NewPointer(4)},
			},
			AccessMode: model.PropertyAccessModeSharedOnly,
		},
		{
			Name:        "start_date",
			DisplayName: "Start Date",
			Type:        model.PropertyFieldTypeDate,
			AccessMode:  model.PropertyAccessModeSourceOnly,
		},
	}
}

func mockEmptyFieldSearch(api *plugintest.API, groupID string) {
	api.On("SearchPropertyFields", groupID, mock.MatchedBy(func(opts model.PropertyFieldSearchOpts) bool {
		return opts.PerPage > 0 && opts.TargetType == "" && len(opts.ObjectTypes) == 0
	})).Return([]*model.PropertyField{}, nil)
}

func TestSyncFields(t *testing.T) {
	groupID := "test-group-id"
	pluginID := "test-plugin-id"
	defs := testFieldDefinitions()

	t.Run("creates all fields and returns ID cache", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock GetPropertyFieldByName returning not found (fields don't exist yet)
		api.On("GetPropertyFieldByName", groupID, "", "job_title").Return(nil, errors.New("not found")).Once()
		api.On("GetPropertyFieldByName", groupID, "", "programs").Return(nil, errors.New("not found")).Once()
		api.On("GetPropertyFieldByName", groupID, "", "clearance").Return(nil, errors.New("not found")).Once()
		api.On("GetPropertyFieldByName", groupID, "", "start_date").Return(nil, errors.New("not found")).Once()

		// Mock field creation - ID is generated by Mattermost
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "job_title" && f.ID == ""
		})).Return(&model.PropertyField{ID: "generated_id_1", Name: "job_title", Type: model.PropertyFieldTypeText}, nil)

		programsField := &model.PropertyField{
			ID:   "generated_id_2",
			Name: "programs",
			Type: model.PropertyFieldTypeMultiselect,
			Attrs: model.StringInterface{
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_1", "name": "Apples"},
					map[string]interface{}{"id": "opt_id_2", "name": "Oranges"},
					map[string]interface{}{"id": "opt_id_3", "name": "Lemons"},
				},
			},
		}
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "programs" && f.ID == ""
		})).Return(programsField, nil)

		clearanceField := &model.PropertyField{
			ID:   "generated_id_3",
			Name: "clearance",
			Type: model.PropertyFieldTypeRank,
			Attrs: model.StringInterface{
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_4", "name": "CUI", "rank": 1},
					map[string]interface{}{"id": "opt_id_5", "name": "Confidential", "rank": 2},
					map[string]interface{}{"id": "opt_id_6", "name": "Secret", "rank": 3},
					map[string]interface{}{"id": "opt_id_7", "name": "Top Secret", "rank": 4},
				},
			},
		}
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "clearance" && f.ID == ""
		})).Return(clearanceField, nil)

		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "start_date" && f.ID == ""
		})).Return(&model.PropertyField{ID: "generated_id_4", Name: "start_date", Type: model.PropertyFieldTypeDate}, nil)
		mockEmptyFieldSearch(api, groupID)

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, defs, summary)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, 4, summary.FieldsCreated)
		assert.Equal(t, 0, summary.FieldsUpdated)
		assert.Equal(t, 0, summary.FieldsDeleted)
		assert.Equal(t, 0, summary.FieldsSkipped)
		assert.Equal(t, "generated_id_1", cache.GetFieldID("job_title"))
		assert.Equal(t, "generated_id_2", cache.GetFieldID("programs"))
		assert.Equal(t, "generated_id_3", cache.GetFieldID("clearance"))
		assert.Equal(t, "generated_id_4", cache.GetFieldID("start_date"))
		assert.Equal(t, model.PropertyFieldTypeText, cache.GetFieldType("job_title"))
		assert.Equal(t, model.PropertyFieldTypeMultiselect, cache.GetFieldType("programs"))
		assert.Equal(t, model.PropertyFieldTypeRank, cache.GetFieldType("clearance"))
		assert.Equal(t, model.PropertyFieldTypeDate, cache.GetFieldType("start_date"))
		assert.Equal(t, "opt_id_1", cache.GetOptionID("programs", "Apples"))
		assert.Equal(t, "opt_id_2", cache.GetOptionID("programs", "Oranges"))
		assert.Equal(t, "opt_id_3", cache.GetOptionID("programs", "Lemons"))
		assert.Equal(t, "opt_id_4", cache.GetOptionID("clearance", "CUI"))
		assert.Equal(t, "opt_id_5", cache.GetOptionID("clearance", "Confidential"))
		assert.Equal(t, "opt_id_6", cache.GetOptionID("clearance", "Secret"))
		assert.Equal(t, "opt_id_7", cache.GetOptionID("clearance", "Top Secret"))
		api.AssertExpectations(t)
	})

	t.Run("updates existing fields", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock GetPropertyFieldByName for each field (simulating they exist)
		existingJobTitle := &model.PropertyField{
			ID:      "existing_id_1",
			GroupID: groupID,
			Name:    "job_title",
			Type:    model.PropertyFieldTypeText,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
			},
		}
		api.On("GetPropertyFieldByName", groupID, "", "job_title").Return(existingJobTitle, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_1"
		})).Return(existingJobTitle, nil).Once()

		existingPrograms := &model.PropertyField{
			ID:      "existing_id_2",
			GroupID: groupID,
			Name:    "programs",
			Type:    model.PropertyFieldTypeMultiselect,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_1", "name": "Apples"},
					map[string]interface{}{"id": "opt_id_2", "name": "Oranges"},
					map[string]interface{}{"id": "opt_id_3", "name": "Lemons"},
				},
			},
		}
		api.On("GetPropertyFieldByName", groupID, "", "programs").Return(existingPrograms, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_2"
		})).Return(existingPrograms, nil).Once()

		existingClearance := &model.PropertyField{
			ID:      "existing_id_3",
			GroupID: groupID,
			Name:    "clearance",
			Type:    model.PropertyFieldTypeRank,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_4", "name": "CUI", "rank": 1},
					map[string]interface{}{"id": "opt_id_5", "name": "Confidential", "rank": 2},
					map[string]interface{}{"id": "opt_id_6", "name": "Secret", "rank": 3},
					map[string]interface{}{"id": "opt_id_7", "name": "Top Secret", "rank": 4},
				},
			},
		}
		api.On("GetPropertyFieldByName", groupID, "", "clearance").Return(existingClearance, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_3"
		})).Return(existingClearance, nil).Once()

		existingStartDate := &model.PropertyField{
			ID:      "existing_id_4",
			GroupID: groupID,
			Name:    "start_date",
			Type:    model.PropertyFieldTypeDate,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
			},
		}
		api.On("GetPropertyFieldByName", groupID, "", "start_date").Return(existingStartDate, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_4"
		})).Return(existingStartDate, nil).Once()
		mockEmptyFieldSearch(api, groupID)

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, defs, summary)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, 0, summary.FieldsCreated)
		assert.Equal(t, 4, summary.FieldsUpdated)
		assert.Equal(t, 0, summary.FieldsDeleted)
		assert.Equal(t, 0, summary.FieldsSkipped)
		assert.Equal(t, "existing_id_1", cache.GetFieldID("job_title"))
		assert.Equal(t, "existing_id_2", cache.GetFieldID("programs"))
		assert.Equal(t, "existing_id_3", cache.GetFieldID("clearance"))
		assert.Equal(t, "existing_id_4", cache.GetFieldID("start_date"))
		api.AssertExpectations(t)
	})

	t.Run("multiselect & rank fields include options", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock GetPropertyFieldByName returning not found for all fields
		api.On("GetPropertyFieldByName", groupID, "", mock.Anything).Return(nil, errors.New("not found"))

		// Mock field creation - verify Programs field has options
		multiSelectOptionsVerified := false
		rankOptionsVerified := false
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			if f.Name == "programs" {
				// Verify Programs field has correct options (Apples, Oranges, Lemons, Grapes)
				options, ok := f.Attrs[model.PropertyFieldAttributeOptions].([]interface{})
				if ok && len(options) == 4 {
					multiSelectOptionsVerified = true
				}
			}
			if f.Name == "clearance" {
				options, ok := f.Attrs[model.PropertyFieldAttributeOptions].([]interface{})

				if ok && len(options) == 4 {
					// Check for Rank as well
					numRanks := 0
					for _, option := range options {
						opt, ok := option.(map[string]interface{})
						if !ok {
							break
						}
						_, ok = opt["rank"]
						if ok {
							numRanks++
						}
					}
					if numRanks == 4 {
						rankOptionsVerified = true
					}
				}
			}
			return true
		})).Return(func(f *model.PropertyField) (*model.PropertyField, error) {
			// Return field with generated ID
			f.ID = "gen_id_" + f.Name
			if f.Name == "programs" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt1", "name": "Apples"},
					map[string]interface{}{"id": "opt2", "name": "Oranges"},
					map[string]interface{}{"id": "opt3", "name": "Lemons"},
					map[string]interface{}{"id": "opt4", "name": "Grapes"},
				}
			}
			if f.Name == "clearance" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt5", "name": "CUI", "rank": 1},
					map[string]interface{}{"id": "opt6", "name": "Confidential", "rank": 2},
					map[string]interface{}{"id": "opt7", "name": "Secret", "rank": 3},
					map[string]interface{}{"id": "opt8", "name": "Top Secret", "rank": 4},
				}
			}
			return f, nil
		})
		mockEmptyFieldSearch(api, groupID)

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID, defs, &Summary{})

		require.NoError(t, err)
		assert.True(t, multiSelectOptionsVerified, "Options should be verified during field creation")
		assert.True(t, rankOptionsVerified, "Ranks should be present on all rank field options")
		assert.NotNil(t, cache)
	})

	t.Run("continues on partial failures", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock GetPropertyFieldByName - all fields don't exist
		api.On("GetPropertyFieldByName", groupID, "", mock.Anything).Return(nil, errors.New("not found"))

		createCallCount := 0
		// First field creation fails, others succeed
		api.On("CreatePropertyField", mock.Anything).Return(func(f *model.PropertyField) (*model.PropertyField, error) {
			createCallCount++
			if createCallCount == 1 {
				// First call fails
				return nil, errors.New("API error")
			}
			// Subsequent calls succeed
			f.ID = "generated_id_" + f.Name
			if f.Name == "programs" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt1", "name": "Apples"},
				}
			}
			if f.Name == "clearance" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt5", "name": "CUI", "rank": 1},
				}
			}
			return f, nil
		})
		mockEmptyFieldSearch(api, groupID)

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogError", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogWarn", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, defs, summary)

		// Should not return error (graceful degradation)
		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, 3, summary.FieldsCreated)
		assert.Equal(t, 0, summary.FieldsUpdated)
		assert.Equal(t, 1, summary.FieldsSkipped)
	})

	t.Run("skipped count accumulates across calls sharing a summary", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		api.On("GetPropertyFieldByName", groupID, "", mock.Anything).Return(nil, errors.New("not found"))
		api.On("CreatePropertyField", mock.Anything).Return(nil, errors.New("API error"))
		mockEmptyFieldSearch(api, groupID)

		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogError", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogWarn", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		failing := defs[:1]
		summary := &Summary{}

		_, err := SyncFields(client, groupID, pluginID, failing, summary)
		require.NoError(t, err)
		_, err = SyncFields(client, groupID, pluginID, failing, summary)
		require.NoError(t, err)

		assert.Equal(t, 2, summary.FieldsSkipped)
	})

	t.Run("empty list creates no fields", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		mockEmptyFieldSearch(api, groupID)
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID, nil, &Summary{})

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Empty(t, cache.FieldNameToID)
		assert.Empty(t, cache.FieldNameToType)
		api.AssertExpectations(t)
	})

	t.Run("deletes omitted plugin-owned fields values first", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		omitted := &model.PropertyField{
			ID:       model.NewId(),
			Name:     "old_title",
			CreateAt: 1,
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		api.On("SearchPropertyFields", groupID, mock.MatchedBy(func(opts model.PropertyFieldSearchOpts) bool {
			return opts.PerPage == fieldSearchPerPage && opts.TargetType == "" && len(opts.ObjectTypes) == 0 && opts.Cursor.PropertyFieldID == ""
		})).Return([]*model.PropertyField{omitted}, nil).Once()
		mock.InOrder(
			api.On("DeletePropertyValuesForField", groupID, omitted.ID).Return(nil).Once(),
			api.On("DeletePropertyField", groupID, omitted.ID).Return(nil).Once(),
		)
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, nil, summary)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, 1, summary.FieldsDeleted)
		api.AssertExpectations(t)
	})

	t.Run("leaves fields owned by an admin or another plugin", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		adminField := &model.PropertyField{
			ID:       model.NewId(),
			Name:     "department",
			CreateAt: 1,
		}
		otherPluginField := &model.PropertyField{
			ID:       model.NewId(),
			Name:     "badge",
			CreateAt: 2,
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: "other.plugin"},
		}
		api.On("SearchPropertyFields", groupID, mock.Anything).Return([]*model.PropertyField{adminField, otherPluginField}, nil).Once()
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID, nil, &Summary{})

		require.NoError(t, err)
		require.NotNil(t, cache)
		api.AssertExpectations(t)
		api.AssertNotCalled(t, "DeletePropertyValuesForField", mock.Anything, mock.Anything)
		api.AssertNotCalled(t, "DeletePropertyField", mock.Anything, mock.Anything)
	})

	t.Run("does not delete fields named in the document", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		keep := defs[0]
		existing := &model.PropertyField{
			ID:       model.NewId(),
			Name:     keep.Name,
			CreateAt: 1,
			Type:     keep.Type,
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		omitted := &model.PropertyField{
			ID:       model.NewId(),
			Name:     "old_title",
			CreateAt: 2,
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		api.On("GetPropertyFieldByName", groupID, "", keep.Name).Return(existing, nil).Once()
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == existing.ID
		})).Return(existing, nil).Once()
		api.On("SearchPropertyFields", groupID, mock.Anything).Return([]*model.PropertyField{existing, omitted}, nil).Once()
		mock.InOrder(
			api.On("DeletePropertyValuesForField", groupID, omitted.ID).Return(nil).Once(),
			api.On("DeletePropertyField", groupID, omitted.ID).Return(nil).Once(),
		)
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, []FieldDefinition{keep}, summary)

		require.NoError(t, err)
		assert.Equal(t, existing.ID, cache.GetFieldID(keep.Name))
		assert.Equal(t, 1, summary.FieldsUpdated)
		assert.Equal(t, 1, summary.FieldsDeleted)
		api.AssertExpectations(t)
		api.AssertNotCalled(t, "DeletePropertyField", groupID, existing.ID)
	})

	t.Run("pages through search results", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		page1 := make([]*model.PropertyField, fieldSearchPerPage)
		for i := range page1 {
			page1[i] = &model.PropertyField{
				ID:       model.NewId(),
				Name:     "old_page1_" + model.NewId(),
				CreateAt: int64(i + 1),
				Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
			}
		}
		page2 := []*model.PropertyField{{
			ID:       model.NewId(),
			Name:     "old_page2",
			CreateAt: int64(fieldSearchPerPage + 1),
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}}
		api.On("SearchPropertyFields", groupID, mock.MatchedBy(func(opts model.PropertyFieldSearchOpts) bool {
			return opts.PerPage == fieldSearchPerPage && opts.Cursor.PropertyFieldID == ""
		})).Return(page1, nil).Once()
		last := page1[len(page1)-1]
		api.On("SearchPropertyFields", groupID, mock.MatchedBy(func(opts model.PropertyFieldSearchOpts) bool {
			return opts.Cursor.PropertyFieldID == last.ID && opts.Cursor.CreateAt == last.CreateAt
		})).Return(page2, nil).Once()
		for _, field := range append(page1, page2...) {
			api.On("DeletePropertyValuesForField", groupID, field.ID).Return(nil).Once()
			api.On("DeletePropertyField", groupID, field.ID).Return(nil).Once()
		}
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, nil, summary)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, fieldSearchPerPage+1, summary.FieldsDeleted)
		api.AssertExpectations(t)
	})

	t.Run("search error aborts deletion and still returns the cache", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		keep := defs[0]
		api.On("GetPropertyFieldByName", groupID, "", keep.Name).Return(nil, errors.New("not found")).Once()
		created := &model.PropertyField{ID: "generated_id_1", Name: keep.Name, Type: keep.Type}
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == keep.Name
		})).Return(created, nil).Once()
		api.On("SearchPropertyFields", groupID, mock.Anything).Return(nil, errors.New("search failed")).Once()
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogError", mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID, []FieldDefinition{keep}, &Summary{})

		require.NoError(t, err)
		assert.Equal(t, created.ID, cache.GetFieldID(keep.Name))
		api.AssertExpectations(t)
		api.AssertNotCalled(t, "DeletePropertyValuesForField", mock.Anything, mock.Anything)
		api.AssertNotCalled(t, "DeletePropertyField", mock.Anything, mock.Anything)
	})

	t.Run("continues after a per-field delete error", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		first := &model.PropertyField{
			ID:       model.NewId(),
			Name:     "broken",
			CreateAt: 1,
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		second := &model.PropertyField{
			ID:       model.NewId(),
			Name:     "stale",
			CreateAt: 2,
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		third := &model.PropertyField{
			ID:       model.NewId(),
			Name:     "stuck",
			CreateAt: 3,
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		api.On("SearchPropertyFields", groupID, mock.Anything).Return([]*model.PropertyField{first, second, third}, nil).Once()
		api.On("DeletePropertyValuesForField", groupID, first.ID).Return(errors.New("values failed")).Once()
		mock.InOrder(
			api.On("DeletePropertyValuesForField", groupID, second.ID).Return(nil).Once(),
			api.On("DeletePropertyField", groupID, second.ID).Return(nil).Once(),
		)
		api.On("DeletePropertyValuesForField", groupID, third.ID).Return(nil).Once()
		api.On("DeletePropertyField", groupID, third.ID).Return(errors.New("field failed")).Once()
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogError", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, nil, summary)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, 1, summary.FieldsDeleted)
		api.AssertExpectations(t)
		api.AssertNotCalled(t, "DeletePropertyField", groupID, first.ID)
	})
}

func TestFieldIDCache(t *testing.T) {
	t.Run("GetFieldID returns correct field IDs", func(t *testing.T) {
		cache := &FieldIDCache{
			FieldNameToID: map[string]string{
				"job_title":  "id1",
				"programs":   "id2",
				"clearance":  "id3",
				"start_date": "id4",
			},
		}
		assert.Equal(t, "id1", cache.GetFieldID("job_title"))
		assert.Equal(t, "id2", cache.GetFieldID("programs"))
		assert.Equal(t, "id3", cache.GetFieldID("clearance"))
		assert.Equal(t, "id4", cache.GetFieldID("start_date"))
	})

	t.Run("GetFieldID returns empty string for unknown field", func(t *testing.T) {
		cache := &FieldIDCache{
			FieldNameToID: make(map[string]string),
		}
		assert.Equal(t, "", cache.GetFieldID("unknown_field"))
	})

	t.Run("GetOptionID returns correct option IDs", func(t *testing.T) {
		cache := &FieldIDCache{
			OptionNameToID: map[string]string{
				"programs|Apples":  "opt1",
				"programs|Oranges": "opt2",
				"programs|Lemons":  "opt3",
			},
		}
		assert.Equal(t, "opt1", cache.GetOptionID("programs", "Apples"))
		assert.Equal(t, "opt2", cache.GetOptionID("programs", "Oranges"))
		assert.Equal(t, "opt3", cache.GetOptionID("programs", "Lemons"))
	})

	t.Run("GetOptionID returns empty string for unknown field", func(t *testing.T) {
		cache := &FieldIDCache{
			OptionNameToID: make(map[string]string),
		}
		assert.Equal(t, "", cache.GetOptionID("unknown", "Apples"))
	})

	t.Run("GetOptionID returns empty string for unknown option", func(t *testing.T) {
		cache := &FieldIDCache{
			OptionNameToID: make(map[string]string),
		}
		assert.Equal(t, "", cache.GetOptionID("programs", "Unknown"))
	})

	t.Run("GetFieldType returns declared types", func(t *testing.T) {
		cache := NewFieldIDCache()
		cache.FieldNameToType["job_title"] = model.PropertyFieldTypeText
		cache.FieldNameToType["clearance"] = model.PropertyFieldTypeRank
		assert.Equal(t, model.PropertyFieldTypeText, cache.GetFieldType("job_title"))
		assert.Equal(t, model.PropertyFieldTypeRank, cache.GetFieldType("clearance"))
		assert.Equal(t, model.PropertyFieldType(""), cache.GetFieldType("unknown_field"))
	})
}

func TestFieldDefinitionDefaults(t *testing.T) {
	tests := []struct {
		name                  string
		json                  string
		wantVisibility        string
		wantAccessMode        string
		wantPermissionField   model.PermissionLevel
		wantPermissionValues  model.PermissionLevel
		wantPermissionOptions model.PermissionLevel
	}{
		{
			name:                  "omitted keys use current defaults",
			json:                  `{"name":"job_title","display_name":"Job Title","type":"text"}`,
			wantVisibility:        model.PropertyFieldVisibilityAlways,
			wantAccessMode:        model.PropertyAccessModePublic,
			wantPermissionField:   model.PermissionLevelSysadmin,
			wantPermissionValues:  model.PermissionLevelSysadmin,
			wantPermissionOptions: model.PermissionLevelSysadmin,
		},
		{
			name:                  "public access_mode translates to empty string",
			json:                  `{"name":"job_title","access_mode":"public"}`,
			wantVisibility:        model.PropertyFieldVisibilityAlways,
			wantAccessMode:        model.PropertyAccessModePublic,
			wantPermissionField:   model.PermissionLevelSysadmin,
			wantPermissionValues:  model.PermissionLevelSysadmin,
			wantPermissionOptions: model.PermissionLevelSysadmin,
		},
		{
			name:                  "empty access_mode is public",
			json:                  `{"name":"job_title","access_mode":""}`,
			wantVisibility:        model.PropertyFieldVisibilityAlways,
			wantAccessMode:        model.PropertyAccessModePublic,
			wantPermissionField:   model.PermissionLevelSysadmin,
			wantPermissionValues:  model.PermissionLevelSysadmin,
			wantPermissionOptions: model.PermissionLevelSysadmin,
		},
		{
			name: "explicit values pass through",
			json: `{
				"name":"start_date",
				"access_mode":"source_only",
				"visibility":"hidden",
				"permission_field":"admin",
				"permission_values":"member",
				"permission_options":"none"
			}`,
			wantVisibility:        model.PropertyFieldVisibilityHidden,
			wantAccessMode:        model.PropertyAccessModeSourceOnly,
			wantPermissionField:   model.PermissionLevelAdmin,
			wantPermissionValues:  model.PermissionLevelMember,
			wantPermissionOptions: model.PermissionLevelNone,
		},
		{
			name:                  "unknown values pass through for the server to reject",
			json:                  `{"name":"x","access_mode":"nope","visibility":"never","permission_field":"root","permission_values":"root","permission_options":"root"}`,
			wantVisibility:        "never",
			wantAccessMode:        "nope",
			wantPermissionField:   model.PermissionLevel("root"),
			wantPermissionValues:  model.PermissionLevel("root"),
			wantPermissionOptions: model.PermissionLevel("root"),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var def FieldDefinition
			require.NoError(t, json.Unmarshal([]byte(tt.json), &def))
			assert.Equal(t, tt.wantVisibility, def.visibility())
			assert.Equal(t, tt.wantAccessMode, def.accessMode())
			assert.Equal(t, tt.wantPermissionField, *def.permissionField())
			assert.Equal(t, tt.wantPermissionValues, *def.permissionValues())
			assert.Equal(t, tt.wantPermissionOptions, *def.permissionOptions())
		})
	}
}
