package sync

import (
	"encoding/json"
	"errors"
	"testing"

	"github.com/mattermost/mattermost/server/public/model"
	"github.com/mattermost/mattermost/server/public/plugin/plugintest"
	"github.com/mattermost/mattermost/server/public/pluginapi"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/mock"
	"github.com/stretchr/testify/require"
)

func testFieldDefinitions() []FieldDefinition {
	return []FieldDefinition{
		{
			Name:        "job_title",
			DisplayName: "Job Title",
			Type:        model.PropertyFieldTypeText,
			AccessMode:  model.PropertyAccessModePublic,
		},
		{
			Name:        "programs",
			DisplayName: "Programs",
			Type:        model.PropertyFieldTypeMultiselect,
			Options: []model.CustomProfileAttributesSelectOption{
				{Name: "Apples"},
				{Name: "Oranges"},
				{Name: "Lemons"},
				{Name: "Grapes"},
			},
			AccessMode: model.PropertyAccessModeSharedOnly,
		},
		{
			Name:        "clearance",
			DisplayName: "Clearance",
			Type:        model.PropertyFieldTypeRank,
			Options: []model.CustomProfileAttributesSelectOption{
				{Name: "CUI", Rank: model.NewPointer(1)},
				{Name: "Confidential", Rank: model.NewPointer(2)},
				{Name: "Secret", Rank: model.NewPointer(3)},
				{Name: "Top Secret", Rank: model.NewPointer(4)},
			},
			AccessMode: model.PropertyAccessModeSharedOnly,
		},
		{
			Name:        "start_date",
			DisplayName: "Start Date",
			Type:        model.PropertyFieldTypeDate,
			AccessMode:  model.PropertyAccessModeSourceOnly,
		},
	}
}

// mockEmptyFieldSearch serves both the ObjectTypes-filtered lookup SyncFields
// does before syncing defs and the unfiltered deletion scan, finding nothing.
func mockEmptyFieldSearch(api *plugintest.API, groupID string) {
	api.On("SearchPropertyFields", groupID, mock.MatchedBy(func(opts model.PropertyFieldSearchOpts) bool {
		return opts.PerPage > 0 && opts.TargetType == ""
	})).Return([]*model.PropertyField{}, nil)
}

// mockFieldLookup serves only the ObjectTypes-filtered lookup, returning the
// given existing fields. The deletion scan's unfiltered search does not match.
func mockFieldLookup(api *plugintest.API, groupID string, fields ...*model.PropertyField) {
	api.On("SearchPropertyFields", groupID, mock.MatchedBy(func(opts model.PropertyFieldSearchOpts) bool {
		return len(opts.ObjectTypes) == 1 && opts.ObjectTypes[0] == model.PropertyFieldObjectTypeUser
	})).Return(fields, nil)
}

func TestSyncFields(t *testing.T) {
	groupID := "test-group-id"
	pluginID := "test-plugin-id"
	defs := testFieldDefinitions()

	t.Run("creates all fields and returns ID cache", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock field creation - ID is generated by Mattermost
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "job_title" && f.ID == "" && f.ObjectType == model.PropertyFieldObjectTypeUser
		})).Return(&model.PropertyField{ID: "generated_id_1", Name: "job_title", Type: model.PropertyFieldTypeText}, nil)

		programsField := &model.PropertyField{
			ID:   "generated_id_2",
			Name: "programs",
			Type: model.PropertyFieldTypeMultiselect,
			Attrs: model.StringInterface{
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_1", "name": "Apples"},
					map[string]interface{}{"id": "opt_id_2", "name": "Oranges"},
					map[string]interface{}{"id": "opt_id_3", "name": "Lemons"},
				},
			},
		}
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "programs" && f.ID == "" && f.ObjectType == model.PropertyFieldObjectTypeUser
		})).Return(programsField, nil)

		clearanceField := &model.PropertyField{
			ID:   "generated_id_3",
			Name: "clearance",
			Type: model.PropertyFieldTypeRank,
			Attrs: model.StringInterface{
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_4", "name": "CUI", "rank": 1},
					map[string]interface{}{"id": "opt_id_5", "name": "Confidential", "rank": 2},
					map[string]interface{}{"id": "opt_id_6", "name": "Secret", "rank": 3},
					map[string]interface{}{"id": "opt_id_7", "name": "Top Secret", "rank": 4},
				},
			},
		}
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "clearance" && f.ID == "" && f.ObjectType == model.PropertyFieldObjectTypeUser
		})).Return(clearanceField, nil)

		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "start_date" && f.ID == "" && f.ObjectType == model.PropertyFieldObjectTypeUser
		})).Return(&model.PropertyField{ID: "generated_id_4", Name: "start_date", Type: model.PropertyFieldTypeDate}, nil)
		mockEmptyFieldSearch(api, groupID)

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, model.PropertyFieldObjectTypeUser, defs, summary)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, 4, summary.FieldsCreated)
		assert.Equal(t, 0, summary.FieldsUpdated)
		assert.Equal(t, 0, summary.FieldsDeleted)
		assert.Equal(t, 0, summary.FieldsSkipped)
		assert.Equal(t, "generated_id_1", cache.GetFieldID("job_title"))
		assert.Equal(t, "generated_id_2", cache.GetFieldID("programs"))
		assert.Equal(t, "generated_id_3", cache.GetFieldID("clearance"))
		assert.Equal(t, "generated_id_4", cache.GetFieldID("start_date"))
		assert.Equal(t, model.PropertyFieldTypeText, cache.GetFieldType("job_title"))
		assert.Equal(t, model.PropertyFieldTypeMultiselect, cache.GetFieldType("programs"))
		assert.Equal(t, model.PropertyFieldTypeRank, cache.GetFieldType("clearance"))
		assert.Equal(t, model.PropertyFieldTypeDate, cache.GetFieldType("start_date"))
		assert.Equal(t, "opt_id_1", cache.GetOptionID("programs", "Apples"))
		assert.Equal(t, "opt_id_2", cache.GetOptionID("programs", "Oranges"))
		assert.Equal(t, "opt_id_3", cache.GetOptionID("programs", "Lemons"))
		assert.Equal(t, "opt_id_4", cache.GetOptionID("clearance", "CUI"))
		assert.Equal(t, "opt_id_5", cache.GetOptionID("clearance", "Confidential"))
		assert.Equal(t, "opt_id_6", cache.GetOptionID("clearance", "Secret"))
		assert.Equal(t, "opt_id_7", cache.GetOptionID("clearance", "Top Secret"))
		api.AssertExpectations(t)
	})

	t.Run("updates existing fields", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		existingJobTitle := &model.PropertyField{
			ID:      "existing_id_1",
			GroupID: groupID,
			Name:    "job_title",
			Type:    model.PropertyFieldTypeText,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
			},
		}
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_1"
		})).Return(existingJobTitle, nil).Once()

		existingPrograms := &model.PropertyField{
			ID:      "existing_id_2",
			GroupID: groupID,
			Name:    "programs",
			Type:    model.PropertyFieldTypeMultiselect,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_1", "name": "Apples"},
					map[string]interface{}{"id": "opt_id_2", "name": "Oranges"},
					map[string]interface{}{"id": "opt_id_3", "name": "Lemons"},
				},
			},
		}
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_2"
		})).Return(existingPrograms, nil).Once()

		existingClearance := &model.PropertyField{
			ID:      "existing_id_3",
			GroupID: groupID,
			Name:    "clearance",
			Type:    model.PropertyFieldTypeRank,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_4", "name": "CUI", "rank": 1},
					map[string]interface{}{"id": "opt_id_5", "name": "Confidential", "rank": 2},
					map[string]interface{}{"id": "opt_id_6", "name": "Secret", "rank": 3},
					map[string]interface{}{"id": "opt_id_7", "name": "Top Secret", "rank": 4},
				},
			},
		}
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_3"
		})).Return(existingClearance, nil).Once()

		existingStartDate := &model.PropertyField{
			ID:      "existing_id_4",
			GroupID: groupID,
			Name:    "start_date",
			Type:    model.PropertyFieldTypeDate,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
			},
		}
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.ID == "existing_id_4"
		})).Return(existingStartDate, nil).Once()
		mockFieldLookup(api, groupID, existingJobTitle, existingPrograms, existingClearance, existingStartDate)
		mockEmptyFieldSearch(api, groupID)

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, model.PropertyFieldObjectTypeUser, defs, summary)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, 0, summary.FieldsCreated)
		assert.Equal(t, 4, summary.FieldsUpdated)
		assert.Equal(t, 0, summary.FieldsDeleted)
		assert.Equal(t, 0, summary.FieldsSkipped)
		assert.Equal(t, "existing_id_1", cache.GetFieldID("job_title"))
		assert.Equal(t, "existing_id_2", cache.GetFieldID("programs"))
		assert.Equal(t, "existing_id_3", cache.GetFieldID("clearance"))
		assert.Equal(t, "existing_id_4", cache.GetFieldID("start_date"))
		api.AssertExpectations(t)
	})

	t.Run("multiselect & rank fields include options", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		// Mock field creation - verify Programs field has options
		multiSelectOptionsVerified := false
		rankOptionsVerified := false
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			if f.Name == "programs" {
				// Verify Programs field has correct options (Apples, Oranges, Lemons, Grapes)
				options, ok := f.Attrs[model.PropertyFieldAttributeOptions].([]interface{})
				if ok && len(options) == 4 {
					multiSelectOptionsVerified = true
				}
			}
			if f.Name == "clearance" {
				options, ok := f.Attrs[model.PropertyFieldAttributeOptions].([]interface{})

				if ok && len(options) == 4 {
					// Check for Rank as well
					numRanks := 0
					for _, option := range options {
						opt, ok := option.(map[string]interface{})
						if !ok {
							break
						}
						_, ok = opt["rank"]
						if ok {
							numRanks++
						}
					}
					if numRanks == 4 {
						rankOptionsVerified = true
					}
				}
			}
			return true
		})).Return(func(f *model.PropertyField) (*model.PropertyField, error) {
			// Return field with generated ID
			f.ID = "gen_id_" + f.Name
			if f.Name == "programs" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt1", "name": "Apples"},
					map[string]interface{}{"id": "opt2", "name": "Oranges"},
					map[string]interface{}{"id": "opt3", "name": "Lemons"},
					map[string]interface{}{"id": "opt4", "name": "Grapes"},
				}
			}
			if f.Name == "clearance" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt5", "name": "CUI", "rank": 1},
					map[string]interface{}{"id": "opt6", "name": "Confidential", "rank": 2},
					map[string]interface{}{"id": "opt7", "name": "Secret", "rank": 3},
					map[string]interface{}{"id": "opt8", "name": "Top Secret", "rank": 4},
				}
			}
			return f, nil
		})
		mockEmptyFieldSearch(api, groupID)

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID, model.PropertyFieldObjectTypeUser, defs, &Summary{})

		require.NoError(t, err)
		assert.True(t, multiSelectOptionsVerified, "Options should be verified during field creation")
		assert.True(t, rankOptionsVerified, "Ranks should be present on all rank field options")
		assert.NotNil(t, cache)
	})

	t.Run("graph field is created with options and parent links inline", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		graphDefs := []FieldDefinition{{
			Name:        "classification",
			DisplayName: "Classification",
			Type:        model.PropertyFieldTypeGraph,
			Options: []model.CustomProfileAttributesSelectOption{
				{Name: "Alpha"},
				{Name: "Alpha-1", Parents: model.NewPointer([]string{"Alpha"})},
			},
		}}

		var sentOptions []interface{}
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			if f.Name != "classification" || f.Type != model.PropertyFieldTypeGraph {
				return false
			}
			options, ok := f.Attrs[model.PropertyFieldAttributeOptions].([]interface{})
			if !ok {
				return false
			}
			sentOptions = options
			return true
		})).Return(&model.PropertyField{
			ID:   "generated_graph_id",
			Name: "classification",
			Type: model.PropertyFieldTypeGraph,
			Attrs: model.StringInterface{
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_a", "name": "Alpha"},
					map[string]interface{}{"id": "opt_id_a1", "name": "Alpha-1"},
				},
			},
		}, nil)
		mockEmptyFieldSearch(api, groupID)

		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, model.PropertyFieldObjectTypeUser, graphDefs, summary)

		require.NoError(t, err)
		assert.Equal(t, 1, summary.FieldsCreated)
		assert.Equal(t, 0, summary.FieldsSkipped)
		require.Len(t, sentOptions, 2)
		root, ok := sentOptions[0].(map[string]interface{})
		require.True(t, ok)
		assert.Equal(t, "Alpha", root["name"])
		assert.NotContains(t, root, "parents")
		child, ok := sentOptions[1].(map[string]interface{})
		require.True(t, ok)
		assert.Equal(t, []interface{}{"Alpha"}, child["parents"])
		assert.Equal(t, "opt_id_a", cache.GetOptionID("classification", "Alpha"))
		assert.Equal(t, "opt_id_a1", cache.GetOptionID("classification", "Alpha-1"))
		api.AssertExpectations(t)
	})

	t.Run("graph field update re-sends parents with the cached option IDs", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		graphDefs := []FieldDefinition{{
			Name:        "classification",
			DisplayName: "Classification",
			Type:        model.PropertyFieldTypeGraph,
			Options: []model.CustomProfileAttributesSelectOption{
				{Name: "Alpha"},
				{Name: "Alpha-1", Parents: model.NewPointer([]string{"Alpha"})},
			},
		}}

		// The server reads a graph field's options back without parent
		// information, so the lookup supplies only the option IDs.
		existing := &model.PropertyField{
			ID:      "existing_graph_id",
			GroupID: groupID,
			Name:    "classification",
			Type:    model.PropertyFieldTypeGraph,
			Attrs: model.StringInterface{
				model.PropertyAttrsSourcePluginID: pluginID,
				model.PropertyFieldAttributeOptions: []interface{}{
					map[string]interface{}{"id": "opt_id_a", "name": "Alpha"},
					map[string]interface{}{"id": "opt_id_a1", "name": "Alpha-1"},
				},
			},
		}

		var sentOptions []interface{}
		api.On("UpdatePropertyField", groupID, mock.MatchedBy(func(f *model.PropertyField) bool {
			if f.ID != "existing_graph_id" {
				return false
			}
			options, ok := f.Attrs[model.PropertyFieldAttributeOptions].([]interface{})
			if !ok {
				return false
			}
			sentOptions = options
			return true
		})).Return(existing, nil).Once()
		mockFieldLookup(api, groupID, existing)
		mockEmptyFieldSearch(api, groupID)

		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		_, err := SyncFields(client, groupID, pluginID, model.PropertyFieldObjectTypeUser, graphDefs, summary)

		require.NoError(t, err)
		assert.Equal(t, 1, summary.FieldsUpdated)
		require.Len(t, sentOptions, 2)
		root, ok := sentOptions[0].(map[string]interface{})
		require.True(t, ok)
		assert.Equal(t, "opt_id_a", root["id"])
		assert.NotContains(t, root, "parents")
		child, ok := sentOptions[1].(map[string]interface{})
		require.True(t, ok)
		assert.Equal(t, "opt_id_a1", child["id"])
		assert.Equal(t, []interface{}{"Alpha"}, child["parents"])
		api.AssertExpectations(t)
	})

	t.Run("a refused graph field is skipped and the rest of the document syncs", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		graphDefs := []FieldDefinition{
			{
				Name:        "classification",
				DisplayName: "Classification",
				Type:        model.PropertyFieldTypeGraph,
				Options: []model.CustomProfileAttributesSelectOption{
					{Name: "Alpha"},
					{Name: "Alpha-1", Parents: model.NewPointer([]string{"Alpha"})},
				},
			},
			{
				Name:        "job_title",
				DisplayName: "Job Title",
				Type:        model.PropertyFieldTypeText,
			},
		}

		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "classification"
		})).Return(nil, errors.New("graph fields are disabled")).Once()
		api.On("CreatePropertyField", mock.MatchedBy(func(f *model.PropertyField) bool {
			return f.Name == "job_title"
		})).Return(&model.PropertyField{ID: "generated_id_1", Name: "job_title", Type: model.PropertyFieldTypeText}, nil).Once()
		mockEmptyFieldSearch(api, groupID)

		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogError", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogWarn", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, model.PropertyFieldObjectTypeUser, graphDefs, summary)

		require.NoError(t, err)
		assert.Equal(t, 1, summary.FieldsCreated)
		assert.Equal(t, 1, summary.FieldsSkipped)
		assert.Equal(t, "generated_id_1", cache.GetFieldID("job_title"))
		assert.Equal(t, "", cache.GetFieldID("classification"))
		api.AssertExpectations(t)
	})

	t.Run("continues on partial failures", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		createCallCount := 0
		// First field creation fails, others succeed
		api.On("CreatePropertyField", mock.Anything).Return(func(f *model.PropertyField) (*model.PropertyField, error) {
			createCallCount++
			if createCallCount == 1 {
				// First call fails
				return nil, errors.New("API error")
			}
			// Subsequent calls succeed
			f.ID = "generated_id_" + f.Name
			if f.Name == "programs" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt1", "name": "Apples"},
				}
			}
			if f.Name == "clearance" {
				f.Attrs[model.PropertyFieldAttributeOptions] = []interface{}{
					map[string]interface{}{"id": "opt5", "name": "CUI", "rank": 1},
				}
			}
			return f, nil
		})
		mockEmptyFieldSearch(api, groupID)

		// Mock logging
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogError", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogWarn", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, model.PropertyFieldObjectTypeUser, defs, summary)

		// Should not return error (graceful degradation)
		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, 3, summary.FieldsCreated)
		assert.Equal(t, 0, summary.FieldsUpdated)
		assert.Equal(t, 1, summary.FieldsSkipped)
	})

	t.Run("skipped count accumulates across calls sharing a summary", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		api.On("CreatePropertyField", mock.Anything).Return(nil, errors.New("API error"))
		mockEmptyFieldSearch(api, groupID)

		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogError", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogWarn", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		failing := defs[:1]
		summary := &Summary{}

		_, err := SyncFields(client, groupID, pluginID, model.PropertyFieldObjectTypeUser, failing, summary)
		require.NoError(t, err)
		_, err = SyncFields(client, groupID, pluginID, model.PropertyFieldObjectTypeUser, failing, summary)
		require.NoError(t, err)

		assert.Equal(t, 2, summary.FieldsSkipped)
	})

	t.Run("empty list creates no fields", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		mockEmptyFieldSearch(api, groupID)
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		cache, err := SyncFields(client, groupID, pluginID, model.PropertyFieldObjectTypeUser, nil, &Summary{})

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Empty(t, cache.FieldNameToID)
		assert.Empty(t, cache.FieldNameToType)
		api.AssertExpectations(t)
	})

	t.Run("lookup search error skips every def without creating", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})

		api.On("SearchPropertyFields", groupID, mock.MatchedBy(func(opts model.PropertyFieldSearchOpts) bool {
			return len(opts.ObjectTypes) == 1 && opts.ObjectTypes[0] == model.PropertyFieldObjectTypeUser
		})).Return(nil, errors.New("search failed"))
		mockEmptyFieldSearch(api, groupID)
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogError", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogWarn", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		cache, err := SyncFields(client, groupID, pluginID, model.PropertyFieldObjectTypeUser, defs, summary)

		require.NoError(t, err)
		require.NotNil(t, cache)
		assert.Equal(t, 0, summary.FieldsCreated)
		assert.Equal(t, 0, summary.FieldsUpdated)
		assert.Equal(t, len(defs), summary.FieldsSkipped)
		assert.Empty(t, cache.FieldNameToID)
		api.AssertExpectations(t)
		api.AssertNotCalled(t, "CreatePropertyField", mock.Anything)
	})

	t.Run("does not delete fields itself", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		mockEmptyFieldSearch(api, groupID)
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		_, err := SyncFields(client, groupID, pluginID, model.PropertyFieldObjectTypeUser, nil, &Summary{})

		require.NoError(t, err)
		api.AssertNotCalled(t, "DeletePropertyValuesForField", mock.Anything, mock.Anything)
		api.AssertNotCalled(t, "DeletePropertyField", mock.Anything, mock.Anything)
	})
}

func TestDeleteOmittedFields(t *testing.T) {
	groupID := "test-group-id"
	pluginID := "test-plugin-id"

	// mockDeletionScan serves only the unfiltered deletion scan, returning the
	// given fields. The ObjectTypes-filtered lookup SyncFields does not match.
	mockDeletionScan := func(api *plugintest.API, fields ...*model.PropertyField) *mock.Call {
		return api.On("SearchPropertyFields", groupID, mock.MatchedBy(func(opts model.PropertyFieldSearchOpts) bool {
			return opts.PerPage == fieldSearchPerPage && opts.TargetType == "" && len(opts.ObjectTypes) == 0 && opts.Cursor.PropertyFieldID == ""
		})).Return(fields, nil)
	}

	t.Run("deletes omitted plugin-owned fields values first", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		omitted := &model.PropertyField{
			ID:         model.NewId(),
			Name:       "old_title",
			ObjectType: model.PropertyFieldObjectTypeUser,
			CreateAt:   1,
			Attrs:      model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		mockDeletionScan(api, omitted).Once()
		mock.InOrder(
			api.On("DeletePropertyValuesForField", groupID, omitted.ID).Return(nil).Once(),
			api.On("DeletePropertyField", groupID, omitted.ID).Return(nil).Once(),
		)
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		DeleteOmittedFields(client, groupID, pluginID, nil, nil, summary)

		assert.Equal(t, 1, summary.FieldsDeleted)
		api.AssertExpectations(t)
	})

	t.Run("leaves fields owned by an admin or another plugin", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		adminField := &model.PropertyField{
			ID:       model.NewId(),
			Name:     "department",
			CreateAt: 1,
		}
		otherPluginField := &model.PropertyField{
			ID:       model.NewId(),
			Name:     "badge",
			CreateAt: 2,
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: "other.plugin"},
		}
		mockDeletionScan(api, adminField, otherPluginField).Once()
		api.On("LogDebug", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		DeleteOmittedFields(client, groupID, pluginID, nil, nil, &Summary{})

		api.AssertExpectations(t)
		api.AssertNotCalled(t, "DeletePropertyValuesForField", mock.Anything, mock.Anything)
		api.AssertNotCalled(t, "DeletePropertyField", mock.Anything, mock.Anything)
	})

	t.Run("does not delete fields named in the document", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		keep := testFieldDefinitions()[0]
		existing := &model.PropertyField{
			ID:         model.NewId(),
			Name:       keep.Name,
			ObjectType: model.PropertyFieldObjectTypeUser,
			CreateAt:   1,
			Type:       keep.Type,
			Attrs:      model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		omitted := &model.PropertyField{
			ID:         model.NewId(),
			Name:       "old_title",
			ObjectType: model.PropertyFieldObjectTypeUser,
			CreateAt:   2,
			Attrs:      model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		mockDeletionScan(api, existing, omitted).Once()
		mock.InOrder(
			api.On("DeletePropertyValuesForField", groupID, omitted.ID).Return(nil).Once(),
			api.On("DeletePropertyField", groupID, omitted.ID).Return(nil).Once(),
		)
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		DeleteOmittedFields(client, groupID, pluginID, []FieldDefinition{keep}, nil, summary)

		assert.Equal(t, 1, summary.FieldsDeleted)
		api.AssertExpectations(t)
		api.AssertNotCalled(t, "DeletePropertyField", groupID, existing.ID)
	})

	t.Run("a channel def does not protect a same-named user field", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		userField := &model.PropertyField{
			ID:         model.NewId(),
			Name:       "classification",
			ObjectType: model.PropertyFieldObjectTypeUser,
			CreateAt:   1,
			Attrs:      model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		mockDeletionScan(api, userField).Once()
		mock.InOrder(
			api.On("DeletePropertyValuesForField", groupID, userField.ID).Return(nil).Once(),
			api.On("DeletePropertyField", groupID, userField.ID).Return(nil).Once(),
		)
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		DeleteOmittedFields(client, groupID, pluginID, nil, []FieldDefinition{{Name: "classification"}}, summary)

		assert.Equal(t, 1, summary.FieldsDeleted)
		api.AssertExpectations(t)
	})

	t.Run("a user def does not protect a same-named channel field", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		channelField := &model.PropertyField{
			ID:         model.NewId(),
			Name:       "classification",
			ObjectType: model.PropertyFieldObjectTypeChannel,
			CreateAt:   1,
			Attrs:      model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		mockDeletionScan(api, channelField).Once()
		mock.InOrder(
			api.On("DeletePropertyValuesForField", groupID, channelField.ID).Return(nil).Once(),
			api.On("DeletePropertyField", groupID, channelField.ID).Return(nil).Once(),
		)
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		DeleteOmittedFields(client, groupID, pluginID, []FieldDefinition{{Name: "classification"}}, nil, summary)

		assert.Equal(t, 1, summary.FieldsDeleted)
		api.AssertExpectations(t)
	})

	t.Run("pages through search results", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		page1 := make([]*model.PropertyField, fieldSearchPerPage)
		for i := range page1 {
			page1[i] = &model.PropertyField{
				ID:       model.NewId(),
				Name:     "old_page1_" + model.NewId(),
				CreateAt: int64(i + 1),
				Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
			}
		}
		page2 := []*model.PropertyField{{
			ID:       model.NewId(),
			Name:     "old_page2",
			CreateAt: int64(fieldSearchPerPage + 1),
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}}
		mockDeletionScan(api, page1...).Once()
		last := page1[len(page1)-1]
		api.On("SearchPropertyFields", groupID, mock.MatchedBy(func(opts model.PropertyFieldSearchOpts) bool {
			return len(opts.ObjectTypes) == 0 && opts.Cursor.PropertyFieldID == last.ID && opts.Cursor.CreateAt == last.CreateAt
		})).Return(page2, nil).Once()
		for _, field := range append(page1, page2...) {
			api.On("DeletePropertyValuesForField", groupID, field.ID).Return(nil).Once()
			api.On("DeletePropertyField", groupID, field.ID).Return(nil).Once()
		}
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		DeleteOmittedFields(client, groupID, pluginID, nil, nil, summary)

		assert.Equal(t, fieldSearchPerPage+1, summary.FieldsDeleted)
		api.AssertExpectations(t)
	})

	t.Run("search error aborts deletion", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		api.On("SearchPropertyFields", groupID, mock.MatchedBy(func(opts model.PropertyFieldSearchOpts) bool {
			return len(opts.ObjectTypes) == 0
		})).Return(nil, errors.New("search failed")).Once()
		api.On("LogError", mock.Anything, mock.Anything, mock.Anything).Maybe()

		DeleteOmittedFields(client, groupID, pluginID, nil, nil, &Summary{})

		api.AssertExpectations(t)
		api.AssertNotCalled(t, "DeletePropertyValuesForField", mock.Anything, mock.Anything)
		api.AssertNotCalled(t, "DeletePropertyField", mock.Anything, mock.Anything)
	})

	t.Run("continues after a per-field delete error", func(t *testing.T) {
		api := &plugintest.API{}
		client := pluginapi.NewClient(api, &plugintest.Driver{})
		first := &model.PropertyField{
			ID:       model.NewId(),
			Name:     "broken",
			CreateAt: 1,
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		second := &model.PropertyField{
			ID:       model.NewId(),
			Name:     "stale",
			CreateAt: 2,
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		third := &model.PropertyField{
			ID:       model.NewId(),
			Name:     "stuck",
			CreateAt: 3,
			Attrs:    model.StringInterface{model.PropertyAttrsSourcePluginID: pluginID},
		}
		mockDeletionScan(api, first, second, third).Once()
		api.On("DeletePropertyValuesForField", groupID, first.ID).Return(errors.New("values failed")).Once()
		mock.InOrder(
			api.On("DeletePropertyValuesForField", groupID, second.ID).Return(nil).Once(),
			api.On("DeletePropertyField", groupID, second.ID).Return(nil).Once(),
		)
		api.On("DeletePropertyValuesForField", groupID, third.ID).Return(nil).Once()
		api.On("DeletePropertyField", groupID, third.ID).Return(errors.New("field failed")).Once()
		api.On("LogInfo", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()
		api.On("LogError", mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything, mock.Anything).Maybe()

		summary := &Summary{}
		DeleteOmittedFields(client, groupID, pluginID, nil, nil, summary)

		assert.Equal(t, 1, summary.FieldsDeleted)
		api.AssertExpectations(t)
		api.AssertNotCalled(t, "DeletePropertyField", groupID, first.ID)
	})
}

func TestFieldIDCache(t *testing.T) {
	t.Run("GetFieldID returns correct field IDs", func(t *testing.T) {
		cache := &FieldIDCache{
			FieldNameToID: map[string]string{
				"job_title":  "id1",
				"programs":   "id2",
				"clearance":  "id3",
				"start_date": "id4",
			},
		}
		assert.Equal(t, "id1", cache.GetFieldID("job_title"))
		assert.Equal(t, "id2", cache.GetFieldID("programs"))
		assert.Equal(t, "id3", cache.GetFieldID("clearance"))
		assert.Equal(t, "id4", cache.GetFieldID("start_date"))
	})

	t.Run("GetFieldID returns empty string for unknown field", func(t *testing.T) {
		cache := &FieldIDCache{
			FieldNameToID: make(map[string]string),
		}
		assert.Equal(t, "", cache.GetFieldID("unknown_field"))
	})

	t.Run("GetOptionID returns correct option IDs", func(t *testing.T) {
		cache := &FieldIDCache{
			OptionNameToID: map[string]string{
				"programs|Apples":  "opt1",
				"programs|Oranges": "opt2",
				"programs|Lemons":  "opt3",
			},
		}
		assert.Equal(t, "opt1", cache.GetOptionID("programs", "Apples"))
		assert.Equal(t, "opt2", cache.GetOptionID("programs", "Oranges"))
		assert.Equal(t, "opt3", cache.GetOptionID("programs", "Lemons"))
	})

	t.Run("GetOptionID returns empty string for unknown field", func(t *testing.T) {
		cache := &FieldIDCache{
			OptionNameToID: make(map[string]string),
		}
		assert.Equal(t, "", cache.GetOptionID("unknown", "Apples"))
	})

	t.Run("GetOptionID returns empty string for unknown option", func(t *testing.T) {
		cache := &FieldIDCache{
			OptionNameToID: make(map[string]string),
		}
		assert.Equal(t, "", cache.GetOptionID("programs", "Unknown"))
	})

	t.Run("GetFieldType returns declared types", func(t *testing.T) {
		cache := NewFieldIDCache()
		cache.FieldNameToType["job_title"] = model.PropertyFieldTypeText
		cache.FieldNameToType["clearance"] = model.PropertyFieldTypeRank
		assert.Equal(t, model.PropertyFieldTypeText, cache.GetFieldType("job_title"))
		assert.Equal(t, model.PropertyFieldTypeRank, cache.GetFieldType("clearance"))
		assert.Equal(t, model.PropertyFieldType(""), cache.GetFieldType("unknown_field"))
	})
}

func TestFieldDefinitionDefaults(t *testing.T) {
	tests := []struct {
		name                  string
		json                  string
		wantVisibility        string
		wantAccessMode        string
		wantPermissionField   model.PermissionLevel
		wantPermissionValues  model.PermissionLevel
		wantPermissionOptions model.PermissionLevel
	}{
		{
			name:                  "omitted keys use current defaults",
			json:                  `{"name":"job_title","display_name":"Job Title","type":"text"}`,
			wantVisibility:        model.PropertyFieldVisibilityAlways,
			wantAccessMode:        model.PropertyAccessModePublic,
			wantPermissionField:   model.PermissionLevelSysadmin,
			wantPermissionValues:  model.PermissionLevelSysadmin,
			wantPermissionOptions: model.PermissionLevelSysadmin,
		},
		{
			name:                  "public access_mode translates to empty string",
			json:                  `{"name":"job_title","access_mode":"public"}`,
			wantVisibility:        model.PropertyFieldVisibilityAlways,
			wantAccessMode:        model.PropertyAccessModePublic,
			wantPermissionField:   model.PermissionLevelSysadmin,
			wantPermissionValues:  model.PermissionLevelSysadmin,
			wantPermissionOptions: model.PermissionLevelSysadmin,
		},
		{
			name:                  "empty access_mode is public",
			json:                  `{"name":"job_title","access_mode":""}`,
			wantVisibility:        model.PropertyFieldVisibilityAlways,
			wantAccessMode:        model.PropertyAccessModePublic,
			wantPermissionField:   model.PermissionLevelSysadmin,
			wantPermissionValues:  model.PermissionLevelSysadmin,
			wantPermissionOptions: model.PermissionLevelSysadmin,
		},
		{
			name: "explicit values pass through",
			json: `{
				"name":"start_date",
				"access_mode":"source_only",
				"visibility":"hidden",
				"permission_field":"admin",
				"permission_values":"member",
				"permission_options":"none"
			}`,
			wantVisibility:        model.PropertyFieldVisibilityHidden,
			wantAccessMode:        model.PropertyAccessModeSourceOnly,
			wantPermissionField:   model.PermissionLevelAdmin,
			wantPermissionValues:  model.PermissionLevelMember,
			wantPermissionOptions: model.PermissionLevelNone,
		},
		{
			name:                  "unknown values pass through for the server to reject",
			json:                  `{"name":"x","access_mode":"nope","visibility":"never","permission_field":"root","permission_values":"root","permission_options":"root"}`,
			wantVisibility:        "never",
			wantAccessMode:        "nope",
			wantPermissionField:   model.PermissionLevel("root"),
			wantPermissionValues:  model.PermissionLevel("root"),
			wantPermissionOptions: model.PermissionLevel("root"),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var def FieldDefinition
			require.NoError(t, json.Unmarshal([]byte(tt.json), &def))
			assert.Equal(t, tt.wantVisibility, def.visibility())
			assert.Equal(t, tt.wantAccessMode, def.accessMode())
			assert.Equal(t, tt.wantPermissionField, *def.permissionField())
			assert.Equal(t, tt.wantPermissionValues, *def.permissionValues())
			assert.Equal(t, tt.wantPermissionOptions, *def.permissionOptions())
		})
	}
}
